
Resources:
  databasestack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://tooba-bucket.s3.amazonaws.com/database.yaml
  webserverstack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: https://tooba-bucket.s3.amazonaws.com/webserver.yaml
      Parameters:
        Myvpc: !GetAtt databasestack.Outputs.Myvpc
        mySecurityGroup: !GetAtt databasestack.Outputs.mySecurityGroup
        wordpressdatabase: !GetAtt databasestack.Outputs.wordpressdatabase
        RdsEndpoint: !GetAtt databasestack.Outputs RdsEndpoint
        PublicSubnetA: !GetAtt databasestack.Outputs PublicSubnetA
        PublicSubnetB: !GetAtt databasestack.Outputs PublicSubnetB
        PrivateSubnetA: !GetAtt databasestack.Outputs PrivateSubnetA
        PrivateSubnetB: !GetAtt databasestack.Outputs PrivateSubnetB
        
